---
title: "Vector Worksheet Redo"
author: "Rachel Feingold"
date: "2/4/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
---
title: "Vector Worksheet Redo"
author: Rachel Feingold
output: html_notebook
---
```{r}
#Problem 1
# a. (1,2,3,...,19,20)
x <- c(1:20)
# b. (20,19,....,2,1)
y <- c(20:1)
# c. (1,2,3,...,19,20,19,18,...,2,1)
z <- c(1:20,19:1)
#d.(4, 6, 3) and assign it to the name tmp.
tmp <- c(4,6,3)
#e. (4, 6, 3, 4, 6, 3,...,4, 6, 3) with 10 occurances of 4
x <- rep(tmp, times=10) 
#or x <- c(answerabve,4)
#f. (4, 6, 3, 4, 6, 3,...,4, 6, 3,4) with 11 occurances of 4
y  <- rep(tmp, times=5, length= 31)
#g. (4, 4, ..., 4, 6, 6, ..., 6, 3, 3, ..., 3) with 10 occurances of 4, 20 occurances of 6, and 30 occurances of 3
z <- rep(tmp, times=c(10,20,30))
```

```{r}
# Problem 2
# Create a vector of values e^(x)cosx at x= 3, 3.1, 3.2, ...,6. Then, make plot of multiplicands and products
x <- seq(3,6, by=.1) # makes a vector for values of x
t <- exp(x)*cos(x) # makes a vector of computed values
plot(t,type="l", col="blue")
points(exp(x),col="red")
points(cos(x), col= "green")
```

```{r}
# Problem 3
# Create vectors
# a. (0.1^3*0.2^1,0.1^6*0.2^4,...,0.1^36*0.2^34)
x <- 0.1^seq(3,36, by=3)
y <- 0.2^seq(1,34, by=3)
t <- x*y
plot(t,type = "l", log = "y", col="blue")
points(x, col="red")
points(y, col="green")
# b. (2, 2^2/2, 2^3/3, ..., 2^25/25)
x <- seq(1,25, by=1)
t <- (2^(x))/x
plot(t,type='l', col="blue")
```

```{r}
# Problem 4. Calculate.
# a. sum(from i=10 to 100)(i^3+4i^2)
i <- 10:100
sum(i^3+4*i^2)
# b. sum(from i=1 to 25)(2^i/i+3^i/i^2)
i <- 1:25
sum((2^i)/i+(3^i)/(i^2))
```

```{r}
# Problem 5. Use the Paste Function to create character vectors of length 30
# a. ("label 1", "label 2", ....., "label 30"). Space between label and the following number
paste("label", 1:30)
# b. ("fn1", "fn2", ..., "fn30"). No spacing between fn and the following number
paste("fn", 1:30, sep='')
```

```{r}
# Problem 6. Creates two vectors of random integers which are chosen with replacement from the integers 0, 1, . . . , 999. Both vectors have length 250.
set.seed(50)
xVec <- sample(0:999, 250, replace=T)
yVec <- sample(0:999, 250, replace=T)
# x =(x1, x2,...,xn) denotes the vector xVec, y =(y1, y2,...,yn) denotes the vector yVec
# a. Create the vector (y2 − x1, . . . , yn − xn−1) and plot it
y1 <- yVec[-1]
v <- c(y1-xVec)
plot(v)
# b.  Create the vector (sin(y1)/cos(x2), sin(y2)/cos(x3), . . . ,sin(yn−1)/cos(xn)) and plot it
x1 <- xVec[-1]
v <- sin(yVec)/cos(x1)
plot(v)
# c. Create the vector (x1 + 2x2 − x3, x2 + 2x3 − x4, . . . , xn−2 + 2xn−1 − xn).
x2 <- xVec[-2:-1]
x1 <- xVec[-1]
v <- xVec+2*x1-x2
plot(v)
# d. calculate sum(i-1 to n-1)(e^-xi+1/x1+10)
sum(exp(-xVec[-1])/(xVec[-length(xVec)] + 10))
```

```{r}
# Problem 7. Use of Functions: sort, order, mean, sqrt, sum, and abs
# a. Pick out the values in yVec which are > 600 and plot as a subset
a <- yVec[yVec>600]
plot(yVec)
points(a,col="red")
# b. Index positions of the values found above
b <- which(yVec>600)
plot(yVec)
points(b,col="red")
# c. What are the values in xVec that correspond to the values in yVec, which are >600
c <- xVec[which(yVec>600)]
plot(xVec)
points(c, col='green')
# d. Create the vector (|x1 − x ̄|^1/2, |x2 − x ̄|^1/2, . . . , |xn −x ̄|^1/2) where x ̄ denotes the mean of the vector.x = (x1, x2, . . . ,xn).
# Make a chart that shows the xVec and the vector created
t <- sqrt(abs(xVec-mean(xVec)))
plot(xVec)
points(t,col='blue')
# e. How many values in yVec are within 200 of the maximum value of the terms in yVec?
sum(yVec>max(yVec)-200)
# f. How many numbers in xVec are divisible by 2? (Note that the modulo operator is denoted %%
sum(xVec%%2==0)
# g. Sort the numbers in the vector xVec in the order of increasing values in yVec. Make a chart
t <- xVec[order(yVec)]
plot(xVec)
points(t, col='red')
# h. Pick out the elements in yVec at index positions 1, 4, 7, 10, 13,... Make a chart
x <- seq(1,250, by=3)
t <- yVec[x]
plot(yVec)
points(t, col='red')
```

```{r}
# Problem 8. Using cumprod function to calculate: 1 + 2/3 + (2/3)(4/5) + ((2/3)(4/5)(6/7)) + ...+ ((2/3)(4/5)...(38/39))
x <- seq(2,38, by=2)
y <- seq(3,39, by=2)
1+sum(cumprod(x/y))
```




```



When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file).
